version: '3'
services:
  test-proj:
    build: .
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=sa
    volumes:
      - .:/app
  h2:
    image: "h2:alpine"
    ports:
      - "8082:8082"
    environment:
      - H2_OPTIONS=-webAllowOthers
