spring:
  application:
    name: test-proj
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:sa}
    driver-class-name: org.h2.Driver
server:
  port: 8080
springdoc:
  swagger-ui:
    path: /swagger-ui.html
